### PR TITLE
Add configurable log level

### PR DESCRIPTION
**Pull request by mhoppal**

### CODE REVIEW

**Comment by tkuhlman** [comment]
This looks basically identical for both the supervisor/nimbus versions. Did I miss some difference or should this be in the general configure.yml task?

**Comment by mhoppal** [comment]
They are identical, the reason I did that is sometimes the nimbus and supervisor will be on different nodes and i need to know which notifier to use as I don't want to restart a service that is not on the node as it will fail. I guess the downfall if it is all on the same node it will only restart the nimbus if it is changed. Also I just noticed that the start.yml checks what is enabled. I will move to the configure.yml task

**Comment by tkuhlman** [comment]
FWIW the handlers check what is enabled also so you can just add both.

**Comment by mhoppal** [comment]
Yeah I meant handlers not start my bad.

**Pull request merged**
